---
version: "2"

services:
  cloudflared:
    image: visibilityspots/cloudflared
    container_name: cloudflared
    ports:
      - "5054:5054/tcp"
      - "5054:5054/udp"
    environment:
        DNS1: 1.1.1.1
        DNS2: 1.0.0.1
        PORT: 5054
        ADDRESS: 0.0.0.0
    restart: always
    environment:
      TZ: '${TIMEZONE}'
    restart: unless-stopped
    networks:
      cloudflared_net:
        ipv4_address: 10.0.0.2

networks:
  cloudflared_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/29
